title: KEEM's PortFolio
email: seok9657@gmail.com
author: Kim KwangSeok
profile: Please contact me if you have any questions.
avatar: "/img/profile.jpg"

github_username:  KEEMKS
instagram_username: czysukeem
blog_username: seok9657

# timezone: Asia/Seoul

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Youtube: https://www.youtube.com/channel/UCuD_fHTE5YwDVCX9aneryjw?view_as=subscriber

baseurl: "myblog"
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
